play_motion:
  motions:
    arms_t:
      joints: [torso_1_joint, torso_2_joint, head_1_joint, head_2_joint, arm_left_1_joint,
        arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint,
        arm_left_7_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.707, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
          0.707, 0.0, 0.1, 0.0, 0.0, 0.0]
        time_from_start: 0.0
      meta:
        name: Arms T
        usage: posture
        description: Both arms set straight pointing sideways at 45 degrees.
    bow:
      joints: [torso_1_joint, torso_2_joint, head_1_joint, head_2_joint, arm_left_1_joint,
        arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint,
        arm_left_7_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.35, 0.17, -0.9, 0.8, 0.1, -0.4, 0.0, 0.35,
          0.17, -0.9, 0.8, 0.1, -0.4, 0.0]
        time_from_start: 0.0
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.35, -0.5, 0.6109, 0.0, 0.0, 0.0, 0.0,
          0.35, -0.5, 0.6109, 0.0, 0.0, 0.0]
        time_from_start: 1.0
      - positions: [0.0, 0.0, 0.0, 0.0, -0.4, 0.25, -0.1, 0.6109, 0.0, 0.0, 0.0, -0.4,
          0.25, -0.1, 0.6109, 0.0, 0.0, 0.0]
        time_from_start: 1.85
      - positions: [0.0, 0.4, 0.0, 0.3, -0.1, 0.1, -0.05, 0.6109, 0.0, 0.0, 0.0, -0.1,
          0.1, -0.05, 0.6109, 0.0, 0.0, 0.0]
        time_from_start: 3.35
      - positions: [0.0, 0.4, 0.0, 0.3, -0.1, 0.1, -0.05, 0.6109, 0.0, 0.0, 0.0, -0.1,
          0.1, -0.05, 0.6109, 0.0, 0.0, 0.0]
        time_from_start: 3.65
      - positions: [0.0, 0.0, 0.0, 0.0, -0.4, 0.1, -0.05, 0.6109, 0.0, 0.0, 0.0, -0.4,
          0.1, -0.05, 0.6109, 0.0, 0.0, 0.0]
        time_from_start: 4.65
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.35, -0.5, 0.6109, 0.0, 0.0, 0.0, 0.0,
          0.35, -0.5, 0.6109, 0.0, 0.0, 0.0]
        time_from_start: 5.5
      - positions: [0.0, 0.0, 0.0, 0.0, 0.35, 0.17, -0.9, 0.8, 0.1, -0.4, 0.0, 0.35,
          0.17, -0.9, 0.8, 0.1, -0.4, 0.0]
        time_from_start: 6.5
      meta:
        name: Bow
        usage: greet
        description: Makes a short reverence with both arms back.
    home:
      joints: [torso_1_joint, torso_2_joint, head_1_joint, head_2_joint, arm_left_1_joint,
        arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint,
        arm_left_7_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 0.0
      meta:
        name: Home
        usage: posture
        description: Both arms down and completely stretched.
    wave:
      joints: [torso_1_joint, torso_2_joint, head_1_joint, head_2_joint, arm_left_1_joint,
        arm_left_2_joint, arm_left_3_joint, arm_left_4_joint, arm_left_5_joint, arm_left_6_joint,
        arm_left_7_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint,
        arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
      points:
      - positions: [0.0, 0.0, 0.0, 0.0, 0.35, 0.17, -0.9, 0.8, 0.1, -0.4, 0.0, 0.35,
          0.17, -0.9, 0.8, 0.1, -0.4, 0.0]
        time_from_start: 0.0
      - positions: [0.0, 0.0, 0.0, 0.0, 0.1, 0.15, 0.0, 0.3, 0.0, 0.0, 0.0, 0.4, 0.15,
          0.4, 2.0, -1.4, 0.6, 0.0]
        time_from_start: 1.5
      - positions: [0.0, 0.0, 0.0, 0.25, 0.1, 0.15, 0.0, 0.3, 0.0, 0.0, 0.0, 0.4,
          0.4, -0.4, 2.0, -1.4, 0.6, 0.0]
        time_from_start: 2.3
      - positions: [0.0, 0.0, 0.0, 0.0, 0.1, 0.15, 0.0, 0.3, 0.0, 0.0, 0.0, 0.4, 0.15,
          0.4, 2.0, -1.4, 0.6, 0.0]
        time_from_start: 3.3
      - positions: [0.0, 0.0, 0.0, 0.0, 0.35, 0.17, -0.9, 0.8, 0.1, -0.4, 0.0, 0.35,
          0.17, -0.9, 0.8, 0.1, -0.4, 0.0]
        time_from_start: 4.3
      meta:
        name: Wave
        usage: greet
        description: Waves with right hand and nods.